name: Build and Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          echo "Installing Python dependencies"
          pip install --upgrade pip  # Ensure pip is up-to-date
          pip install zipp==3.0.0
          pip install pathlib2==2.3.5
          pip install -U --upgrade mkdocs==1.4.2
          pip install Pygments==2.14.0
          pip install pymdown-extensions==9.10
          pip install mkdocs-minify-plugin==0.6.2
          pip install mkdocs-markdownextradata-plugin==0.2.5
          pip install mkdocs-redirects==1.2.0
          pip install pathlib==1.0.1
          pip install -U mkdocs-material==9.1.2
          pip install markdown-include==0.8.1
          pip install markdown==3.2.1
          pip install mkdocs-exclude==1.0.2
          pip install -U Jinja2==3.1.0
          pip install mkdocs-glightbox==0.3.4
          pip install mkdocs-include-markdown-plugin==1.0.0
          pip install mkdocs-open-in-new-tab==1.0.3

      # Step 4: Install Node.js tools (for markdown-spellcheck and markdown-link-check)
      - name: Install Node.js tools
        run: |
          echo "Installing npm tools"
          npm i markdown-spellcheck@1.3.1 -g
          npm install -g markdown-link-check@3.10.3

      - name: Create site directory
        run: mkdir -p en/site

      # Step 5: Build MkDocs site using config from the 'en' directory
      - name: Build MkDocs site
        run: |
          mkdocs build --config-file en/mkdocs.yml --site-dir en/site
    
          
      # Step 6: Move built content to 'en/site'
      - name: Move built content to 'en/site'
        run: |
         mv site/* en/site/ || echo "No files to move"

       # Step 7: Commit and push changes to the repository
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "nashaathniz@gmail.com"
          git add en/site
          git commit -m "Auto-deploy MkDocs content to en/site"
          git push origin main
