name: Build and Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          echo "Installing Python dependencies"
          pip install --upgrade pip  # Ensure pip is up-to-date
          pip install zipp==3.0.0
          pip install pathlib2==2.3.5
          pip install -U --upgrade mkdocs==1.4.2
          pip install Pygments==2.14.0
          pip install pymdown-extensions==9.10
          pip install mkdocs-minify-plugin==0.6.2
          pip install mkdocs-markdownextradata-plugin==0.2.5
          pip install mkdocs-redirects==1.2.0
          pip install pathlib==1.0.1
          pip install -U mkdocs-material==9.1.2
          pip install markdown-include==0.8.1
          pip install markdown==3.2.1
          pip install mkdocs-exclude==1.0.2
          pip install -U Jinja2==3.1.0
          pip install mkdocs-glightbox==0.3.4
          pip install mkdocs-include-markdown-plugin==1.0.0
          pip install mkdocs-open-in-new-tab==1.0.3

      # Step 4: Install Node.js and mdspell
      - name: Install mdspell and markdown-link-check
        run: |
          echo "Installing npm tools"
          npm install -g markdown-link-check@3.10.3
          npm install -g mdspell@2.2.0

      # Step 5: Run mdspell to check markdown spelling
      - name: Check markdown spelling
        run: |
          mdspell -V
          mdspell -n -a --en-us docs/**/*.md -d dictionary/en_US-large
          mdspell -n -a --en-us docs/**/**/*.md -d dictionary/en_US-large
          mdspell -n -a --en-us mkdocs.yml -d dictionary/en_US-large
          mdspell -n -a --en-us theme/material/templates/home-page2.html -d dictionary/en_US-large

      # Step 6: Check markdown links
      - name: Check markdown links
        run: |
          find docs/** -type f -name '*.md' | xargs -L1 markdown-link-check -c ./markdown-link-check-config.json --quiet || exit 1
          find docs/**/* -type f -name '*.md' | xargs -L1 markdown-link-check -c ./markdown-link-check-config.json --quiet || exit 1

      # Step 7: Build MkDocs site
      - name: Build MkDocs site
        run: |
          mkdocs build -c

      # Step 8: List files in the site directory
      - name: List built content
        run: |
          ls site/
