name: Build and Deploy MkDocs

# Trigger the workflow when a PR is merged into the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Step 3: Install dependencies (MkDocs and MkDocs Material)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      # Step 4: Build MkDocs site
      - name: Build MkDocs site
        run: mkdocs build

      # Step 5: Move built content to 'site/en'
      - name: Move built content to 'site/en'
        run: |
          mkdir -p site/en
          mv site/* site/en/ || true

      # Step 6: Commit and push the changes to the repository
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add site/en
          git commit -m "Auto-deploy MkDocs content to site/en"
          git push
